# 1. Rocky Linux 8.10 버전을 base 이미지로 설정
FROM rockylinux/rockylinux:8.10.20240528

# 2. 시스템 업데이트 및 필요한 패키지 설치 (wget, make, gcc, perl, zlib-devel, gcc-c++ 포함)
RUN dnf -y update && \
    dnf -y groupinstall "Development Tools" && \
    dnf -y install wget gcc make perl-Digest-SHA zlib-devel gcc-c++ && \
    dnf -y install expat-devel && \
    dnf -y install libtool perl-Pod-Html  perl-IPC-Cmd && \
    dnf clean all

# 3. OpenSSL 3.3.1 설치 (명시적으로 Linux 빌드 설정)
RUN wget https://www.openssl.org/source/openssl-3.3.1.tar.gz && \
       tar -xvzf openssl-3.3.1.tar.gz
RUN cd openssl-3.3.1 && \
       ls -ltr && \
       ./config && \
       make && make install && \
       ln -sf /usr/local/bin/openssl /usr/bin/openssl && \
       cd .. && rm -rf openssl-3.3.1.tar.gz openssl-3.3.1 

# 4. PCRE2 10.44 설치
RUN wget https://github.com/PhilipHazel/pcre2/releases/download/pcre2-10.44/pcre2-10.44.tar.gz && \
    tar -xvzf pcre2-10.44.tar.gz && \
    cd pcre2-10.44 && \
    ./configure && \
    make && make install && \
    cd .. && rm -rf pcre2-10.44.tar.gz pcre2-10.44

# 5. APR 1.7.4 설치
RUN wget https://dlcdn.apache.org/apr/apr-1.7.5.tar.gz && \
    tar -xvzf apr-1.7.5.tar.gz && \
    cd apr-1.7.5 && \
    ./configure && \
    make && make install && \
    cd .. && rm -rf apr-1.7.5.tar.gz apr-1.7.5

# 5. APR UTIL 1.6.3 설치
RUN pwd && \
       ls -ltr && \
       ls -ltr /usr/local
RUN wget https://dlcdn.apache.org//apr/apr-util-1.6.3.tar.gz && \
    tar -xvzf apr-util-1.6.3.tar.gz && \
    cd apr-util-1.6.3 && \
    ./configure --prefix=/usr/local/apr --with-apr=/usr/local/apr && \
    make && make install && \
    cd .. && rm -rf apr-util-1.6.3.tar.gz apr-util-1.6.3


# 6. Apache 2.4.62 버전 설치 (OpenSSL 3.3.1, PCRE2 10.44, APR 1.6.4 지원)
RUN wget https://dlcdn.apache.org/httpd/httpd-2.4.62.tar.gz && \
    tar -xvzf httpd-2.4.62.tar.gz && \
    cd httpd-2.4.62 && \
    ./configure --enable-ssl --enable-so --with-included-apr --with-ssl=/usr/local --with-pcre=/usr/local --with-apr=/usr/local && \
    make && make install && \
    rm -rf /httpd-2.4.62.tar.gz /httpd-2.4.62

# 7. 포트 80과 443 (HTTP, HTTPS) 열기
EXPOSE 80 443

# 8. Apache 실행
CMD ["/usr/local/apache2/bin/httpd", "-DFOREGROUND"]
